name: aula02_combustivel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  #sdk: ^3.7.0
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/aog-white.png   
  fonts:
    - family: Big Shoulders Display
      fonts:
        - asset: assets/fonts/bigshouldersdisplay-light.ttf